### ISSUE TITLE
FEAT:  Settings page

### ISSUE THREAD

**Issue by seanvree** [Monitorr/Monitorr#24]
**Updated**: jonfinley 3/5
**Feature**:  Integrated Settings Page

**STATUS**: Pushing to master

**Current Branch**: Develop

BUGS:

- [x] 	 Form validation to check for trailing slash   https://github.com/DrRoach/FormValidation/issues/1
- [x] 	New Alpaca version breaks the default select option: https://github.com/gitana/alpaca/issues/612
- [x] 	Services Form Layout won’t render in two-column – https://github.com/gitana/alpaca/issues/610
- [x] 	Service Settings: Radio Buttons uncheck when switching order 
- [x] URL validation for rox puny code shit?! WTF https://en.wikipedia.org/wiki/Punycode

Progress:

- [x] (Complete) Development
- [x] (Complete) Functionality
- [x] (Complete) Pushed to Alpha
- [x] (Complete) Test: Windows
- [x] (Complete) Test: Docker
- [x] (Complete) Test: Linux
- [x] (Complete) UI Android
- [x] (Complete) UI iOS: 
- [x] (Complete) Merged to DEV
- [x] (Pending) Merged with master
- [x] (Pending) Release published

Individual setting pages:

1.	Info:

- [x] 	 PHPInfo
- [x] 	Update check/execute
- [x]  Github link / Docker Hub link
- [x] 	Donate Link
- [x]	CSS

2.	User Preferences:

- [x]	Site Title
- [x]	Site URL
- [x]	Language??
- [x] Time Standard
- [x]	Time Zone (!issue)
- [x]	Update Branch
- [x]	UN & PW

- [x]	CSS

3.	Monitorr Settings:

- [x]	Alert Banner enable/disable
- [x]	Refresh sysinfo
- [x]	Refresh Time 
- [x]	Ping Host
- [x]	Ping Port
- [x]	CPU OK
- [x]	CPU Warn
- [x]	RamOK
- [x]	RamWarn
- [x]	HD OK 
- [x]	HD Warn 
- [x]	CSS

4.	Services:

- [x]	Service Title 
- [x]	Service Image 
- [x]	Check Type
- [x]	Check URL – DONE
- [x]	Link URL – DONE
- [x]	Offline Link URL - LATER
- [x]	Authentication - LATER
- [x]	CSS

**Comment by jonfinley** [comment]
```
function config_set($config_file, $section, $key, $value) {
    $config_data = parse_ini_file($config_file, true);
    $config_data[$section][$key] = $value;
    $new_content = '';
    foreach ($config_data as $section => $section_content) {
        $section_content = array_map(function($value, $key) {
            return "$key=$value";
        }, array_values($section_content), array_keys($section_content));
        $section_content = implode("\n", $section_content);
        $new_content .= "[$section]\n$section_content\n";
    }
    file_put_contents($config_file, $new_content);
}
```
#46

**Comment by seanvree** [comment]
UI theme:

https://codepen.io/SkyHyzer/pen/BLygaP

**Comment by seanvree** [comment]
Alternate solution:

https://stackoverflow.com/questions/2015715/fastest-way-to-store-easily-editable-config-data-in-php

**Comment by seanvree** [comment]
https://stackoverflow.com/questions/10840308/writing-a-configuration-file-in-php

**Comment by seanvree** [comment]
Need to use this as our source for data tables and "database" 

https://datatables.net/download/#bs/dt-1.10.11,fh-3.1.1,r-2.0.2

@jonfinley

**Comment by jonfinley** [comment]
i brought in a lot of the code from PLPP into settings2, create a new config folder. need to discuss services. I might have an idea.

**Comment by seanvree** [comment]
@jonfinley  SICK! We'll talk tomo

**Comment by seanvree** [comment]
Pushed to develop

**Comment by seanvree** [comment]
added with version 1.5.0m

https://github.com/Monitorr/Monitorr/releases
