### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by wjbeckett** [Monitorr/Monitorr#44]
The README is a little confusing at the moment so might be good to reorganize it and make the instructions a little clearer for new users.

#### Tasks:
- [x] Editing Config file instructions
- [x] Adding custom images instructions
- [x] Display major known bugs
- [x] Add main features
- [ ] Donation link
